- hosts: mysql app gitlab runner monitoring
  gather_facts: true
  become:
    true
  become_method:
    sudo
  become_user:
    root
  remote_user:
    ubuntu
  roles:
   - update
   - node_exporter
  environment:
     http_proxy: http://uralhouse.site:8118
     https_proxy: http://uralhouse.site:8118
